server:
   port: 9090

spring:
   application:
      name: zuul
      
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:9091/eureka/
zuul:  
   routes:
     AIRLINESERVICE:    
         path: /stocks/**
         url:  STOCKSERVICE
     LOGINSERVICE:
         path: /authenticate/**
         url:  LOGINSERVICE
     BOOKINGSERVICE:
         path: /company/**
         url:  COMPANYSERVICE


jwt:
   secret:javainuse